import { writeFile, getCacheDirectory } from '@adapters/expo/file-system';
import { shareFile } from '@adapters/expo/sharing';
import { serializeCube } from '@lut-core/cube/cube-serializer';
import type { LutMetadata } from '@lut-core/model/lut-metadata';
import { DEFAULT_DOMAIN_MAX, DEFAULT_DOMAIN_MIN } from '@lut-core/model/lut-metadata';
import type { LutTable } from '@lut-core/model/lut-table';

export interface ExportedCube {
  readonly uri: string;
  readonly filename: string;
}

export async function exportLutAsCube(table: LutTable, name: string): Promise<ExportedCube> {
  const metadata: LutMetadata = {
    title: name,
    size: table.size,
    domainMin: DEFAULT_DOMAIN_MIN,
    domainMax: DEFAULT_DOMAIN_MAX,
    comments: ['Generated by LUT App'],
  };
  const cubeText = serializeCube(table, metadata);
  const sanitizedName = name.trim().length > 0 ? name : 'lut-app-export';
  const filename = `${sanitizedName.replace(/[^a-zA-Z0-9_-]/g, '_')}.cube`;
  const uri = `${getCacheDirectory()}${filename}`;

  await writeFile(uri, cubeText);

  return { uri, filename };
}

export async function shareLutAsCube(table: LutTable, name: string): Promise<void> {
  const { uri } = await exportLutAsCube(table, name);
  await shareFile(uri, 'application/octet-stream');
}
