import { parseCube } from '@lut-core/cube';
import { LutTable, lutTableIndex } from '@lut-core/model';

function makeIdentityLut(size: number): LutTable {
  const data = new Float32Array(size * size * size * 3);

  for (let blue = 0; blue < size; blue += 1) {
    for (let green = 0; green < size; green += 1) {
      for (let red = 0; red < size; red += 1) {
        const offset = lutTableIndex(red, green, blue, size);
        data[offset] = red / (size - 1);
        data[offset + 1] = green / (size - 1);
        data[offset + 2] = blue / (size - 1);
      }
    }
  }

  return { size, data };
}

function makeMinimalCubeText(size: number): string {
  const lut = makeIdentityLut(size);
  const lines = ['TITLE "Identity"', `LUT_3D_SIZE ${size}`];

  for (let index = 0; index < lut.data.length; index += 3) {
    lines.push(`${lut.data[index]} ${lut.data[index + 1]} ${lut.data[index + 2]}`);
  }

  return lines.join('\n');
}

describe('parseCube', () => {
  it('parses a valid 2x2x2 cube file into a LUT table', () => {
    const result = parseCube(makeMinimalCubeText(2));

    expect(result.ok).toBe(true);
    if (!result.ok) {
      return;
    }

    expect(result.value.table.size).toBe(2);
    expect(Array.from(result.value.table.data.slice(0, 6))).toEqual([0, 0, 0, 1, 0, 0]);
  });

  it('parses a valid 33x33x33 cube file', () => {
    const result = parseCube(makeMinimalCubeText(33));

    expect(result.ok).toBe(true);
    if (!result.ok) {
      return;
    }

    expect(result.value.table.size).toBe(33);
    expect(result.value.table.data).toHaveLength(33 * 33 * 33 * 3);
  });

  it('returns an error when LUT_3D_SIZE is missing', () => {
    const result = parseCube('TITLE "Broken"\n0.0 0.0 0.0');

    expect(result.ok).toBe(false);
    if (!result.ok) {
      expect(result.error.code).toBe('CUBE_MISSING_SIZE');
    }
  });

  it('returns an error when the data row count is wrong', () => {
    const result = parseCube('TITLE "Broken"\nLUT_3D_SIZE 2\n0 0 0');

    expect(result.ok).toBe(false);
    if (!result.ok) {
      expect(result.error.code).toBe('CUBE_INVALID_DATA_COUNT');
    }
  });

  it('returns an error for NaN values', () => {
    const result = parseCube(
      [
        'TITLE "Broken"',
        'LUT_3D_SIZE 2',
        '0 0 0',
        '1 0 0',
        '0 1 0',
        '1 1 0',
        '0 0 1',
        '1 0 1',
        '0 1 NaN',
        '1 1 1',
      ].join('\n'),
    );

    expect(result.ok).toBe(false);
    if (!result.ok) {
      expect(result.error.code).toBe('CUBE_INVALID_NUMBER');
    }
  });

  it('parses TITLE and DOMAIN values correctly', () => {
    const result = parseCube(
      [
        '# generated by test',
        'TITLE "Film Look"',
        'DOMAIN_MIN 0.1 0.2 0.3',
        'DOMAIN_MAX 0.9 0.8 0.7',
        'LUT_3D_SIZE 2',
        ...makeMinimalCubeText(2).split('\n').slice(2),
      ].join('\n'),
    );

    expect(result.ok).toBe(true);
    if (!result.ok) {
      return;
    }

    expect(result.value.metadata.title).toBe('Film Look');
    expect(result.value.metadata.domainMin).toEqual([0.1, 0.2, 0.3]);
    expect(result.value.metadata.domainMax).toEqual([0.9, 0.8, 0.7]);
  });
});
